### ISSUE TITLE
prototype - css-in-js (glam)

### ISSUE THREAD

**Issue by threepointone** [kentcdodds/babel-macros#1]
making this issue and assigning to myself, to make a prototype of glam that's compatible with this package, just to prove that it's possible.  

the idea is to get this - https://github.com/facebookincubator/create-react-app/issues/2730#issuecomment-313356440 to "work".

**Comment by threepointone** [comment]
oh, please assign this to me when you can :)

**Comment by threepointone** [comment]
up for grabs, if anyone else wants to take a crack at it - 
- relay 
- preval (kent, I assume you'll try this one yourself?)

**Comment by EnoahNetzach** [comment]
Would this macro prototype also work for e.g. styled components? 

If not, I'll be glad to contribute with a tailored one!

**Comment by threepointone** [comment]
I'm just working on a small prototype to prove that it works, if you want something more full featured/matching the SC api, you're likely better off integrating with emotion  https://github.com/tkh44/emotion since they already have much of the compliation work done

**Comment by EnoahNetzach** [comment]
Thank you for pointing me to `emotion`, but I wanted to try to prototype a SC macro to work with Create React App 😉.

**Comment by threepointone** [comment]
styled-components already works in SC (by nature of being a pure runtime lib), not sure what you'd use the macro for?

**Comment by threepointone** [comment]
oh is it for this? https://github.com/styled-components/babel-plugin-styled-components go for it, could be useful

**Comment by EnoahNetzach** [comment]
yep!

**Comment by kentcdodds** [comment]
Done! You can now use `preval` without adding the `preval` plugin to your babel config. Simply add `babel-macros` to your plugins instead, then:

```javascript
import preval from 'babel-plugin-preval/macros'

const x = preval`
  module.exports = Math.random()
`
```

And poof, it works. Can also do a function call or JSX :) Fun stuff.

**Comment by kentcdodds** [comment]
Gonna close this in favor of https://github.com/tkh44/emotion/issues/132
