### ISSUE TITLE
import a macro to run on the whole program

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/babel-macros#13]
What do people think of this?

```
import './some.macro'
```

And we call `some.macro` with the `Program` node. 🤔 

This would allow you to add some explicitness to plugins that doesn't really have any api calls. Like [`transform-react-constant-elements`](https://babeljs.io/docs/plugins/transform-react-constant-elements/)

Thoughts?

**Comment by tricoder42** [comment]
1. How about plugins for different environments? `import` is static, can't be wrapped in if. The logic could be inside macro, though.

2. I'm still worried that soon we end up copy-pasting subset of .babelrc to each file. I understand it's clear and explicit, I just don't like it :) Some plugins should be really implicit, so you don't have to worry about them (what if you forget? How do you check that all files with JSX have this macro?)

**Comment by kentcdodds** [comment]
Yeah, after discussing this further with @threepointone on [twitter](https://twitter.com/threepointone/status/885231456854913025) I'm convinced that this could definitely be a part of another package, but it's technically not a macro so we wont do it in this package.
