### ISSUE TITLE
Macros referencing local objects

### ISSUE THREAD

**Issue by tricoder42** [kentcdodds/babel-macros#15]
Right now, macros are *unbound* functions:

```js
import translate from 'i18n/macro'

translate`Hello ${name}`

// becomes
translate('Hello {name}', { name })
```

However, some macros might require reference to local objects. In the example above, `translate` function should receive `i18n`object holding translations and active language:

```js
import i18n from 'i18n' // fictional i18n lib
import translate from 'i18n/macro'

translate`Hello {name}`

// should be
i18n.translate('Hello {name}', { name })
// or
translate(i18n, 'Hello {name}', { name }) 
```

In React it's easy, because components have access to context:

```js
import Translate from 'i18n-react/macro'

<Translate>Hello {name}</Translate>

// becomes
<Translate id="Hello {name}" values={{ name }} />
```

and component will access `i18n` configuration from context.

However, I don't have an idea how to handle this with JS functions. `i18n` might have different name (so we can't simply compile `translate` to `i18n.translate`), when initialized locally. However, it could be enforced that `translate` macro requires `i18n` in scope (as React is required when using JSX)

**Attempt 1**

If we allowed runtime configuration of macros, it would have to be configured in every file, given the explicit nature of macros:

```js
import { i18n } from 'i18n'
import translate from 'i18n/macro'

// need to be explicit in every file -> error prone
translate.use(i18n)

translate`Hello {name}`
```

**Attempt 2**

Pass `i18n` as an argument to macro. Macro will process all AST nodes, so this should work:

```js
translate(i18n, `Hello ${name}`)
```

but I just dislike this syntax (compared to `i18n.translate`Hello {name}`)

Any ideas? So far enforcing `i18n` in scope seems to be easiest way to go.

**Comment by kentcdodds** [comment]
Yeah, I think this is a bit of an edge case, but I expected something like this to be required so we have an escape hatch. You can use the reference path you're given to find the program node. Then you search that for the import. It's sub optimal, but it shouldn't be more than three or four lines of code. This might help: https://github.com/babel-utils/babel-explode-module but it might do more than you need...

**Comment by tricoder42** [comment]
Yep, that sounds good. Read the imports, check for i18n (or i18n variable defined in top scope) and raise warning if it's missing. 

I'm going to convert two babel plugins into macros. Curious how it's gonna work.

Thanks 👍

**Comment by kentcdodds** [comment]
Awesome! Hopefully we can get a few more common plugins to do so as well and get CRA to adopt it!
