### ISSUE TITLE
reference to similar ideas - Sweet.js

### ISSUE THREAD

**Issue by EnoahNetzach** [kentcdodds/babel-macros#2]
If it could be useful inspiring some solutions for this package, there is also the very active [**Sweet.js**](https://github.com/sweet-js/sweet-core) to look at.

**Comment by kentcdodds** [comment]
There's a reference in the README... Is that what you mean?

**Comment by EnoahNetzach** [comment]
I actually did see that, but shortly after forgot...

My bad!
