### ISSUE TITLE
Finding available macros

### ISSUE THREAD

**Issue by mattphillips** [kentcdodds/babel-macros#21]
Hey I was thinking it might be useful to keep a list of available macros out in the wild in this repo?

I've just published support for `babel-macros` in [babel-plugin-console](https://github.com/mattphillips/babel-plugin-console#macros).

I know the infamous [babel-plugin-preval](https://github.com/kentcdodds/babel-plugin-preval#use-with-babel-macros) supports macros.

Any others?

I'm happy to send a PR documenting the list of existing macros :smile:

Also I've created the following badge to celebrate this package 🎉 

[![Babel Macro](https://img.shields.io/badge/babel--macro-%F0%9F%8E%A3-f5da55.svg?style=flat-square)](https://github.com/kentcdodds/babel-macros)

**Comment by kentcdodds** [comment]
Great idea! Why don't we ask that packages add the keyword `babel-macros` to their packages, then we could just direct people to the npm page for that keyword: https://www.npmjs.com/browse/keyword/babel-macros

> Also I've created the following badge to celebrate this package 🎉

Oh I love this. I love it very much 👍 

So let's get the README updated with docs :+1: wanna do that?

**Comment by mattphillips** [comment]
Sure I'll send a PR :smile:

**Comment by vinhlh** [comment]
Supported `babel-macros` to my tiny package https://github.com/vinhlh/tagged-translations.

I love `babel-macros` idea.
`babel-macros` also helps my code looks naturally, without having a global reference to `t`.
```js
import t from 'tagged-translations/macro';

const HelloComponent = ({ name }) => (
  <div>
    {t`Hello ${name}`}
  </div>
)
```

looking forward to being integrated into `create-react-app` 🎉🎉🎉

P/S: btw, I am looking for the way to set options for `macro` (may be somewhere in app scope).

**Comment by kentcdodds** [comment]
> P/S: btw, I am looking for a right solution to set options for `macro` (may be somewhere in app scope).

File a new issue. I have some ideas around this...

**Comment by kentcdodds** [comment]
> Supported `babel-macros` to my tiny package [vinhlh/tagged-translations](https://github.com/vinhlh/tagged-translations).

:tada:

**Comment by kentcdodds** [comment]
I went ahead and did this. Thanks again!

Note: right now there are only 2 packages listed on [npm with the `babel-macros` keyword](https://www.npmjs.com/browse/keyword/babel-macros)! But [there are more](https://libraries.io/npm/babel-macros/usage)... I'm sure folks would love PRs to add the keyword to their package.json :smile:

**Comment by mattphillips** [comment]
@kentcdodds sorry dude I completely let this slip! Thanks for sorting it out :smile:

**Comment by kentcdodds** [comment]
No worries. If you wanna make it up to me, you could look at #20 or #22 :wink:

Not that you owe me :smile:
