### ISSUE TITLE
Add default error handling wrapper.

### ISSUE THREAD

**Issue by tkh44** [kentcdodds/babel-macros#22]
Suggested solution:

Add a try/catch around wherever you apply the macro so that macros will have better error handling out of the box.

Bonus points:
Add a way for macros to identify themselves including a link to their repo for issues.

**Comment by kentcdodds** [comment]
Love this idea 👍

**Comment by kentcdodds** [comment]
Just talked with @threepointone about this and it's definitely something we want to do. I'm thinking that we'll want to add a try/catch around the macro call and throw a useful error (and allow the macro to identify itself as you suggested, though we already know the source of the import so we should have a good default here). One other thing we'll want to support is some mechanism for the macro to throw a special error that we just forward (`class MacroError extends Error`?) so macro authors can throw custom errors that are even more helpful.

Happy to accept a PR for this if anyone wants to work on it. I'll comment in here once I've started if nobody else takes it first. Thanks!
