### ISSUE TITLE
Npm test fails on clean clone (Windows)

### ISSUE THREAD

**Issue by erik-lundgren** [kentcdodds/babel-macros#23]
- `babel-macros` version: current master [d2ee8fc](https://github.com/kentcdodds/babel-macros/commit/d2ee8fc201aa9721e632d828c5ba8fe3d32f3a11)
- `node` version: v8.4.0
- `npm` (or `yarn`) version: 5.3.0 (yarn: v0.21.3)

Getting the following error when running the tests:

```
Cannot find module 'fake/macro' from 'index.js'
```

What you did:
http://imgur.com/a/50zxy
git clone
cd babel-macros
npm install
npm test

What happened:
http://imgur.com/a/50zxy
```
> babel-macros@0.5.2 test [Path/to/babel-macros]
> nps test

nps is executing `test` : jest --coverage
 FAIL  src\__tests__\index.js
  ● Test suite failed to run

    Cannot find module 'fake/macro' from 'index.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (src/__tests__/index.js:3:14)
```

Reproduction repository:
This is it!

Problem description:
Seems to be something wrong with jest's mocked module resolution on windows. Importing from `fake\\mock` works. Babel-jest or jest is probably assuming it's a path and windows-ifies it. 

Suggested solution:
Either wait for jest to fix the issue or import without the `/`.

**Comment by kentcdodds** [comment]
> Seems to be something wrong with jest's mocked module resolution on windows. Importing from fake\\mock works. Babel-jest or jest is probably assuming it's a path and windows-ifies it.

That's very interesting! Do you think you could create a small repo that reproduces that issue and file that in `jest`? Seems like that could be a big issue!

**Comment by kentcdodds** [comment]
Thank you for doing this digging!

**Comment by erik-lundgren** [comment]
I'll reference this issue from babel-jest as soon as I have made it.

**Comment by erik-lundgren** [comment]
Created https://github.com/facebook/jest/issues/4284 for babel-jest.

**Comment by kentcdodds** [comment]
Perfect. Thank you!

**Comment by kentcdodds** [comment]
I think this is fixed. Thanks!
