### ISSUE TITLE
Proposal: integrate babel-plugin-ast-literal

### ISSUE THREAD

**Issue by caesarsol** [kentcdodds/babel-macros#28]
What would you think about implementing something similar to [`babel-plugin-ast-literal`](https://github.com/andreypopp/babel-plugin-ast-literal)?

I'm doing it here https://github.com/caesarsol/traph.macro/blob/master/macro.js and seems very useful.

Wonderful project BTW, it's what I was waiting for!

**Comment by caesarsol** [comment]
I think I'll maybe start by building a macro for AST generation!

Do you think it would be possible for `babel-macros` to execute itself on the macro definitions? This would make it possible for macro authors to not transpile their code before publishing.

**Comment by kentcdodds** [comment]
> Do you think it would be possible for babel-macros to execute itself on the macro definitions?

If you're asking whether babel-macros should transpile your macro ahead of running it (via babel-register or similar), then I think no, I don't really want to do that... If you'd like to not transpile, then you can require babel-register yourself.

**Comment by kentcdodds** [comment]
> What would you think about implementing something similar to babel-plugin-ast-literal?

Not sure what you mean. Could you elaborate?

Also, thanks for joining the community! 🤗

**Comment by caesarsol** [comment]
Sorry for my vagueness, I mean to give the users a function to build the AST more easily, as I did in my example using the ast-literal plugin.

**Comment by kentcdodds** [comment]
Gotcha! Thanks! It's unclear to me the advantage over babel-template. Could you explain?

**Comment by caesarsol** [comment]
I think the main difference is performance: since the transpilation step absorbs the paraing there's no duplicated work.
Second I had difficulties substituting an objectExpression, is that supported? Can't babel-template substitute only identifiers?
I think it's all described in the project readme. I could do a bit more research though.

**Comment by kentcdodds** [comment]
Gotcha, thanks!

> performance: since the transpilation step absorbs the paraing there's no duplicated work.

That makes sense that it would be faster, but babel-template is fast enough, so that's not reason enough for me to add support/complexity.

> Second I had difficulties substituting an objectExpression, is that supported? Can't babel-template substitute only identifiers?

I've not found that to be an issue personally.

Because it's really easy for folks to add their own dependencies, I think that's what we're going to do. If you'd like to add a note to the README about `babel-plugin-ast-literal` that'd be fine with me :)

**Comment by caesarsol** [comment]
Thanks for your feedback!

I'm going to try replicate the issue I had with `babel-template` and I'll see if I can add something 😄

**Comment by kentcdodds** [comment]
I'm going to go ahead and close this for now.
