### ISSUE TITLE
Feature request: Support JSX attribute nodes

### ISSUE THREAD

**Issue by scottmas** [kentcdodds/babel-macros#31]
Hey Kent, I'd like to create a macro that is triggered on an JSX attribute node, in the same way that this  babel plugin transforms attribute nodes: https://github.com/insin/babel-plugin-react-html-attrs/blob/master/lib/index.js

However, when I declare a macro and put it on an attribute, the transform function never fires.

```javascript
//some.macro.js
const {createMacro} = require('babel-macros');

module.exports = createMacro(({references, babel}) => {
  console.log("Visiting some AST node...")
})
```

```javascript
//input.js
import React from 'react'
import macro from 'some.macro.js'

function SomeComponent(){
  return <div macro={123}>Hi there</div>
}
```
but compiling shows that the node is never traversed:
```bash
babel input.js -o output.js
# The console statement never prints...
```

**Comment by kentcdodds** [comment]
This is because the `references` you get are references to what you're importing. Unfortunately an attribute is not a reference. To make it one, you'd have to make it a computed property like this:

```jsx
import React from 'react'
import macro from 'some.macro'

function SomeComponent(){
  return <div {...{[macro]: 123}}>Hi there</div>
}
```

IMO that's not ergonomic enough to make the macro worth it.

One other thing you could do is write your macro so that it gets the program node and transpiles the entire file. I think that wouldn't be too terrible... But it does miss out on some of the benefits of babel-macros...

**Comment by scottmas** [comment]
Ha, that's a clever workaround. So the whole premise of babel-macros is that macros can be explicit (the `.macro` extension) and so that it requires zero .babelrc configuration. Would it be keeping in lines with the ethos of the library to have global escape function that gives devs full access to the babel AST tree? Potentially some scoping could be enforced by the `createMacro` wrapper, so that it's not a complete free for all.

I'm thinking something along the lines of

```javascript
//some.macro.js
const { createTopLevelMacro } = require('babel-macros');
const traverse = require('babel-traverse');

module.exports = createTopLevelMacro({
    visitor: {
      JSXElement(path) {
         path.traverse({
	       JSXAttribute: function(node) {
	        //Do stuff to node
	      }
	    })	
      }
    }
});
```

```javascript
//babel-macros
export function createTopLevelMacro(defs){
  Object.keys(defs.visitor || {}).forEach(fn => {
      // decorate fn to ensure scoping so that it only gets called when properly called
  })
}
```

Would something like this be in keeping with the goals of babel-macros?

**Comment by kentcdodds** [comment]
`babel-macros` wont do that, but you _can_ get the program node and traverse that yourself. I don't have time to give you a good example, but you can definitely make it work without any changes to `babel-macros`.

**Comment by kentcdodds** [comment]
I'm going to go ahead and close this as it's not actionable.

**Comment by bySabi** [comment]
@scottmas did you get it solved?

I've been trying to do the same: macro support for babel-plugin-react-html-attrs
