### ISSUE TITLE
macro vs function calls

### ISSUE THREAD

**Issue by cztomsik** [kentcdodds/babel-macros#35]
I hope I get right that this really is a way to replace AST at compile time - I love that idea!

Is there any way to indicate that this is macro rather than regular function call? Something like 
`myMacro!(...)` in [rust](https://doc.rust-lang.org/1.10.0/book/macros.html)?

If not and the reason is babel can't parse that, maybe I could help with that.

**Comment by kentcdodds** [comment]
Hi @cztomsik!

Thanks for the issue. I'm pretty strongly against syntax changes to support macros unless it becomes a part of the language. A big reason is editor and parser support. Adding syntax gets pretty messy.

So thanks for the suggestion, but we wont be doing that.

**Comment by cztomsik** [comment]
I respect that but macros can:

- define new variables
- generate expressions with access to scope `s(name)` -> `this.state.name`
- change the meaning of hashes, array literals, anything
- it can ignore the code entirely

So basically, once you use macros, there is no javascript anymore and editors and linting might get as much confused as people could. Special syntax would certainly help to people at least.

**Comment by kentcdodds** [comment]
You make decent points, however most of the time the editor stuff will still work without showing red squiggly lines due to syntax issues and that's what I want to avoid. People are already helped plenty by the explicit import, I think adding syntax would confuse them more than it would help them.

**Comment by kentcdodds** [comment]
But if you really feel strongly about this, you can always fork. But I'm definitely not interested in doing this. Sorry.

**Comment by cztomsik** [comment]
Ok, thank you anyway :)
