### ISSUE TITLE
named exports

### ISSUE THREAD

**Issue by threepointone** [kentcdodds/babel-macros#5]
libs like emotion will need to export multiple macros, so babel-macros could support named exports, such that the following works. 

```jsx
import { styled, css } from 'emotion/macros'

let red = css` color: red `

let Heavy = styled('div')`
  composes: ${red};
  font-weight: bold;
`

// ... etc ...
```

**Comment by kentcdodds** [comment]
Ok, so I changed the API a little bit to accommodate for allowing you to process each named import in the order you need so you can do what you need to. See [this example](https://github.com/kentcdodds/babel-macros/blob/master/src/__tests__/fixtures/emotion.macros.js) of the API. Right now this only works for import. Wont work for destructuring requires (yet).

Let me know if that works for you.

**Comment by kentcdodds** [comment]
Just [updated the preval macros](https://github.com/kentcdodds/babel-plugin-preval/commit/600beb823d974e03b5d2d318ea6cc956d9e13ba4)
