### ISSUE TITLE
How to identify a macros

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/babel-macros#7]
Right now we identify a macros if the import/require source string matches [this regex](https://github.com/kentcdodds/babel-macros/blob/1b120c52474d5f9a33be9c38e1e4fd02751a0c05/src/index.js#L4): `/[./]macros(\.js)?$/`

@gaearon [mentioned](https://github.com/facebookincubator/create-react-app/issues/2730#issuecomment-313554085):

> The only thing I don’t quite like is the `.macros` naming, maybe we can come up with an alternative suffix.

@threepointone [suggested](https://github.com/facebookincubator/create-react-app/issues/2730#issuecomment-313572422):

> The _ideal_ solution would be to have separate syntax, e.g. `importMacros`, but that's likely never going to happen
> Another option is to use a webpack inspired 'babel-macros?css', but that straight up looks alien
> Alternate words off the top of my head - mods, plugs, socks(?), defines

So then I [said](https://github.com/facebookincubator/create-react-app/issues/2730#issuecomment-313581416):

> I want to make sure that existing tooling will work as much as I can so I want to avoid anything too weird looking... 🤔
> 
> I don't mind macros myself, but happy to consider other names 👍

To which @gaearon [replied](https://github.com/facebookincubator/create-react-app/issues/2730#issuecomment-313648256):

> The thing is, it also need to be explicit enough that you wouldn’t mistake it from a regular import. Because otherwise it’ll be a debugging nightmare for the person who doesn’t know what’s going on.

Then @suchipi [suggested](https://github.com/facebookincubator/create-react-app/issues/2730#issuecomment-313734669):

> Flow has `import type`, and sweet.js uses `import ... for syntax`. Is adding a similar syntax extension to babylon going too far for something like this?

And finally I [said](https://github.com/facebookincubator/create-react-app/issues/2730#issuecomment-313740175):

> I'd be fine with it if babylon supported it via a plugin, then people could just include a preset we make (and CRA could include it in its own config theoretically). I like:
> 
> ```
> import macros glam from 'glam.macros'
> ```
> 
> But I'm open to pretty much anything else.

---

So now that we're all caught up, let's discuss the options. Other people I'd love to get input from are: @hzoo, @loganfsmyth, and @jlongster :smile:

Here are the options as I see them:

1. babylon plugin for new syntax
2. matching imports where the source matches a regex

Any other ideas?

**Comment by gaearon** [comment]
I guess let’s go with `.macros` naming for now and revisit after we have real world feedback from using it.

**Comment by kentcdodds** [comment]
Sounds fine to me. I expect that if it's changed we could write a codemod to upgrade people's code in a pretty straightforward way anyway :smile:

Still open to other thoughts though!

**Comment by hzoo** [comment]
I'd say I'd like to stay away from having to handle new syntax in Babel itself? Although we made exceptions in the past for JSX/Flow/TS and same with proposals - we aren't adding anything if it's not proposed to TC39?

**Comment by kentcdodds** [comment]
Sounds good. I think the best way forward is to continue as we are. I find it very unlikely that something like this would make it to the TC39 ever (I don't even know how that'd work) because it's a compile-time thing. We'll see what the future holds. Thanks for the input @hzoo!

**Comment by kentcdodds** [comment]
Going to go ahead and close this for now. Happy to hear other thoughts though.

**Comment by suchipi** [comment]
This kind of really doesn't matter, but...
```js
import css from "glam.macros"
```
Using "macros" (the plural) is kinda weird since that file only exports one macro.
Should we consider maybe doing `.macro`?

**Comment by kentcdodds** [comment]
Yes, I'll make that change right now. Thanks!

**Comment by kentcdodds** [comment]
Done. Thanks again! :+1: `v0.5.0`

**Comment by tricoder42** [comment]
What if there're more macros?

```js
import { Translation, Plural, Select } from 'i18n.macros'
```

I guess it could be written on separate lines, but it's just shorter/faster.

**Comment by kentcdodds** [comment]
What you have there is totally supported (except the source must end in macro). See [this](https://github.com/kentcdodds/babel-macros/blob/master/src/__tests__/index.js#L68) and [this](https://github.com/kentcdodds/babel-macros/blob/master/src/__tests__/fixtures/emotion.macro.js).

Though that's a good point. Perhaps we should support both `macro` and `macros`?

**Comment by tricoder42** [comment]
I really don't mind about naming, whatever works. Let's stick to `macro` ;)  I thought I read through test cases, but I definitely missed that.

Awesome work!

**Comment by suchipi** [comment]
I don't see too much of an issue supporting both `macro` and `macros`. Only downside I can think of would be documentation/learning overhead.

**Comment by kentcdodds** [comment]
Yeah, I think that we should probably only have one (`macro`) and stick with that... Otherwise it will make things confusing.

**Comment by anikethsaha** [comment]
>  I find it very unlikely that something like this would make it to the TC39 ever (I don't even know how that'd work) because it's a compile-time thing

I guess the ecosystem need something named **CT39** - **Compile-Time 39**
😁
