### ISSUE TITLE
Question: Clarify use case

### ISSUE THREAD

**Issue by tricoder42** [kentcdodds/babel-macros#9]
Hello,
I'm just trying to wrap my head around is.

Suppose we have a lib `precompile`. Instead of:

1. Add babel-plugin-precompile
2. Import function

We're going to have:

0. Add babel-preset-macros (only once)
1. Import function from `precompile.macros`

Is that correct? (I changed numbering on purpose, so it's clear that babel-macros are one step easier)

My questions are:

1. How is determined order of plugins? I believe *precompilation* should be done first before *compilation*, but what if some plugins/macros will require to come after?
2. I saw only examples using tagged template literals. Does this solution work also for other elements? For example, I'm precompiling anything between `<Trans>` tags inside React.
3. How does it work for plugins, which does general code optimization, like [transform-react-constant-elements](https://babeljs.io/docs/plugins/transform-react-constant-elements/)? I.e: plugins, which you don't import in code, but rather works implicitly.

Thank you! I'm really hoping this will grow in usable solution. I'm willing to help anytime! 👍

**Comment by kentcdodds** [comment]
Your assumptions are correct. Here are the answers:

1. Order is determined by the order of the import/require statements, so it's up to the user. I think that this is actually a really nice feature because currently ordering in babel is a real challenge/frustration.
2. macros functions are given all references to things that are imported, so it works with _anything_. (including JSX) See [this](https://github.com/kentcdodds/babel-macros/blob/master/src/__tests__/__snapshots__/index.js.snap) for some examples.
3. The point of `babel-macros` is that nothing is implicit. I think that's part of the beauty of it as well. If you _need_ it to be implicit, then that wont work with `babel-macros`.

These answers would go great in a FAQ that's referenced in the README. Care to add that?

**Comment by tricoder42** [comment]
> 1. Order is determined by the order of the import/require statements, so it's up to the user. I think that this is actually a really nice feature because currently ordering in babel is a real challenge/frustration.

Yes, definitely. But I guess, it also depends on order of `babel-macros` in Babel config, right? User is able to only reorder macros which are processed in `babel-macros`:

```
{
  "presets": [
    "env",
    "react",
    "babel-macros"  # 1st preset to run, all macros run at this stage
  ]
}
```

… but in this setup, there's no way to run a macro *after* env preset.

Not saying it's a bad thing. It's just I know how preset/plugin ordering is painful in Babel right now and this was my first concern.

> 2. macros functions are given all references to things that are imported, so it works with anything. (including JSX) See this for some examples.

Yes, I saw that but misunderstood it. I get it now, thanks 👍 

> 3. The point of babel-macros is that nothing is implicit. I think that's part of the beauty of it as well. If you need it to be implicit, then that wont work with babel-macros.

There're some [expectations](https://github.com/facebookincubator/create-react-app/issues/2730#issuecomment-313549964) that `babel-macros` could add some missing features to zero-config boilerplates. One of them are decorators. I think we would either need different syntax for decorators or an *implicit* macro.

My other concern is personal as I need to process AST tree to extract messages (similar what `https://github.com/yahoo/babel-plugin-react-intl` does).

However, I understand it's not what babel-macros are intended to solve. There's gonna be probably different solution.

> These answers would go great in a FAQ that's referenced in the README. Care to add that?

Sure thing, I'll write it down (probably by the end of this week, as I'm a bit busy atm).

Thanks a lot again! 👍
